### PR TITLE
docs: fix typo in README.md

### PR DESCRIPTION
**Pull request by pgrimaud**
Hi,

This tiny PR will fix : 

- 1 typo in `README.md`

Cheers! :robot:

### CODE REVIEW

**Comment by josepot** [comment]
Thanks!

@all-contributors please add @pgrimaud for docs

**Comment by josepot** [comment]
Hi @pgrimaud 

Thanks a lot for the PR!

If you don't mind me asking, though: how did you come across this project? We are still finishing the docs, improving the tests and polishing the release of `v0.2.0`. I was planing to publicly announce it once those 3 things are done. So, I'm a bit curious to know how it was that you came across this project? 

Once again, thanks for fixing that typo!

Also, if you like RxJS and React, please stay tuned for the release of `v0.2.0`.

Cheers,

Josep

**Comment by pgrimaud** [comment]
> If you don't mind me asking, though: how did you come across this project? We are still finishing the docs, improving the tests and polishing the release of `v0.2.0`. I was planing to publicly announce it once those 3 things are done. So, I'm a bit curious to know how it was that you came across this project?

I'm working on a typo bot fixer. It parsing GitHub search with last activity of repositories.
Then I made a manual review to double check typos and ensure a personal technology watch.

😄

**Comment by josepot** [comment]
> I'm working on a typo bot fixer. It parsing GitHub search with last activity of repositories.

:joy: Amazing! Well, thanks a lot for the contribution!

**Pull request merged**
